spring:
  application:
    name: keepgo
  datasource:
    url: jdbc:${DB_VENDOR:mysql}://${DB_HOST:172.25.96.1}:${DB_PORT:3306}/${DB_NAME:keepgo}?serverTimezone=${DB_TIMEZONE:Asia/Seoul}
    username: ${DB_USERNAME:keepgo}
    password: ${DB_PASSWORD:0000}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    database-platform: org.hibernate.dialect.${DB_DIALECT:MySQL}Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:451367164829-umjho06iuhcmapqlk7f0ebesllrbsukq.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - openid
              - profile
              - email
